language: cpp

os:
  - linux

env:
  global:
    - secure: "bOQIp6c4XWY1gtQK8XL5APYAmDWcuQmplE8L+fCGcEHA5rhPQ1HXXULjRsr+IoEG6BEby1eeX1Pzrgb5VQswtgzlqvYUZpvgfy5sQO/OnprTFzSia7UUjshgSM7HQ1t64xCAAxUI1r9ejzh75ROUC140LtqF1TmMz3JOU87cLwX5PPd1nRNgVXTv4LfxEUV4zw0Zw/a3Doo1CEBtpvFFWve+uHrvznFYRCdm1EcBxjeJ8aoLTUnd83Vm3yzF+UlZ04SIofrW9BvYG82aBYqNrpVBU+bUAruWipa/r0WE219zlwr9nCSfgrzDymIQLSxCvNDV0sbDz0yvOD4hjKcBrj6tIZBe/RNDoFdVN9R+54nq4OJNtF9F8gh4L1A9CjJzI1Xtu8fePTcKwgKT+tUHnDd3sfxZHdG59lIJKOYw0FJi0HF6qQk8ZguufQL1WakAEyMM3GIxuv7FxfDGt2ztzwahF1C5qHfVBOL5jcEmGz6+9xgStDH9jjxkb3mVeHTb9E8D1zjerM4uP13NFe2qgg4cEWqDONJuUE6eZLaEVEp/SsRB6zQ+vfB3fZ/Sdf7GcNTC0mKIN/OObKB4Ouev6X8gLZDeTJE1kHt+USLkA1j/pOK7CcTskCSYu+VJZJWySKgLfE11xhZ31nU6R7PLpegrhPMRkdVONDzGwQ6FzvU="
    - secure: "vq99sJ2apAhG/Zp74EOFBeUL35XxuIpghoqSU0VizNouvx93E3g01rkhhEq20WadxAPMc0oFoUXBHo2p10XCYqxpN2MpN4IMc+rCoSx6G/ZRDZTRbS0AWlZyQAmHOIP5GEHCneU0ES8WZtUeJKeoVwgOAo7woSxYd4zdpPP5xnE1DEy7EhD2+r+wIC09Q5yUo+2aAzvEPLjWJK/9HH0H64YHALMghvFpq3iy86xkQ80I9935QivV3nsPSFG4Cz9AHmn4R4BAwybKM8uoxoROQQyRK5qrGnAmXnICOeafiRldd03CbCgiAfw4PmB4XgeBhk+sGU8o94zkZRU6GUT94LBAVEN01xC2ctFMX9ILcRd5gTXCALwHX/rvHIG8GUMhx1ivqWPvl4swgE6ddBsoZzSpjUDYxRewLajm96mKQkLCLEzkDG+H9VUfB+imWIvLgJloV71BPpRicFyo/sNxzAncqpYml4xPr2dSRjzNuoBq4b8GKIJWb9Y8lwtBsXad3m1h3CHXrs6PanZDM2O25W8/NSNthb5lEKENgFhWUuZpeETS5wmAlMpPFtTCSudX5nPuZbufy2D27yA7ut5n3RnZGintHoF5M/390ksF1+XkNqEjJgyDFrty0LHOwaTYlXmlbf/dyuQBGxw6DnPfzr0zTynViQf4lhcw6/GU150="
  matrix:
    - CONFIG=Debug
    - CONFIG=Release

script:
  - wget https://ricochet.im/releases/1.1.0/ricochet-1.1.0-static-x86_64.tar.bz2
  - tar czf Data_${CONFIG}_${TRAVIS_BUILD_NUMBER}.tar.bz2 ricochet-1.1.0-static-x86_64.tar.bz2

after_success:
  - "curl --ftp-create-dirs -T Data_${CONFIG}_${TRAVIS_BUILD_NUMBER}.tar.bz2 -u $FTPUSER:$FTPPASS ftp://k1.kolodziej.in/builds/kolodziej"