language: cpp

os:
  - linux

env:
  global:
    ftpdata:
      - secure: "D8232Npdf5AVm28QG6A9PBxYqWXazJubh46nSLFa/7q5pt4eXTGdLk/Sd1fugQaMn0zD8/Zd+9GbrU3OSAeRrOCGfcZP7JZqTfJJTWrV7PiWXn7dY5G1TuQc5EDZ6oivCcc8vY6Zq/oVQxgFAUuGT6/KvYtPeLE+NNcv9jklmAchvLdUFBl6j26csTtPTdMBhTiUPhT99g8Ywkwc2qKAvgt16iX1RX76BDJ+GlvpXfiBDt3sQyC8yyaVYFqiefH4Tq6maXceieV7aR7hcHUR8BxFY7AwhRE/oZ7jn6jGcajhJUERVyR84U747zJHWwFtCwIXqkTJ08TzuISyibkJ3+hqFqU7Dq/OV3EuzlaDfaZTHROw9lsGTd9VIX7djXoIDQKHjXxKc6y4mdnaDR+tW9pQS0rP/kNu5jo1B1NljTBJOnPRr3xHgDRLVYg0HsHZlM+MkqL5yY3UOIRcuOt4hKKNrcynNMpe/kcsqgKffMvpjmyDclCt0ivOB0ldeIE1kw6A+UnJMwFaEbmVJt/+w0Q5w4CWs+0yjvHGfDMmCdIrZvE2CJGbGMuajtlIQCm1L5kQpwQ/ZFi1uOAdQ7jJUHbQZu2439SawJL+9f7+WN6pPvv618ZfXH5QnhWNv9QH+ldMf+r+NAaMWjC5ykeXuNPaSHDN8XOosgPwISCM4ME="
  - CONFIG=Debug
  - CONFIG=Release

script:
  - wget https://kolodziej.in/index.html
  - tar czf index.html Data_$CONFIG_$TRAVIS_BUILD_NUMBER.tar.bz2

after_success:
  - "curl --ftp-create-dirs -T git@github.com:kolodziej/CI-test-deploy.git -u $ftpdata ftp://k1.kolodziej.in/builds/kolodziej"