language: cpp

os:
  - linux

env:
  global:
    - secure: "bOQIp6c4XWY1gtQK8XL5APYAmDWcuQmplE8L+fCGcEHA5rhPQ1HXXULjRsr+IoEG6BEby1eeX1Pzrgb5VQswtgzlqvYUZpvgfy5sQO/OnprTFzSia7UUjshgSM7HQ1t64xCAAxUI1r9ejzh75ROUC140LtqF1TmMz3JOU87cLwX5PPd1nRNgVXTv4LfxEUV4zw0Zw/a3Doo1CEBtpvFFWve+uHrvznFYRCdm1EcBxjeJ8aoLTUnd83Vm3yzF+UlZ04SIofrW9BvYG82aBYqNrpVBU+bUAruWipa/r0WE219zlwr9nCSfgrzDymIQLSxCvNDV0sbDz0yvOD4hjKcBrj6tIZBe/RNDoFdVN9R+54nq4OJNtF9F8gh4L1A9CjJzI1Xtu8fePTcKwgKT+tUHnDd3sfxZHdG59lIJKOYw0FJi0HF6qQk8ZguufQL1WakAEyMM3GIxuv7FxfDGt2ztzwahF1C5qHfVBOL5jcEmGz6+9xgStDH9jjxkb3mVeHTb9E8D1zjerM4uP13NFe2qgg4cEWqDONJuUE6eZLaEVEp/SsRB6zQ+vfB3fZ/Sdf7GcNTC0mKIN/OObKB4Ouev6X8gLZDeTJE1kHt+USLkA1j/pOK7CcTskCSYu+VJZJWySKgLfE11xhZ31nU6R7PLpegrhPMRkdVONDzGwQ6FzvU="
    - secure: "iR25o0xgt8g9u8o6pR9L6HqAt+XOZMDZ2N4gQduxENow7DfnxMSMA14ozG0Lp/jvUC6O46f98U4cmbBbVZzXaJB/vlMVt9+FDuvcMac2mwnQ5QWPCTojVNXAH6q5ISvltv4cV/Uuzkw2GkMkNvHEnBzrMuWv6GsjLkMQlAjaRqpVu7IIBktpFv8lXqvAgbOBJw0QxaBQOjSRDF29CCafsa9PUB74euwF6yNAW8OqNi1ms3TTjhUvsTXYg4hvllO8+jzEZ4tLTcB3zOgHz7q8/L3fsv7BwKp7MRUEL5F2rm7yMUQQvQmwo5gGKrYKyUp2+z2gwlCN5sduOuC5nnC0m94MQ8HkgcOU/Vm++C9iaaWGMupTII0x8Q+TYEOTO2GuUOrc724ngaQkoTEkexbjyl5PpGR/pB6CuAsJFP8KfR2y8t/vu7GMfCeJwLlkqK2tidg7KqF8exwsJGMeBb1ZFHu7zyiS4Sut6BSHyebWGo+r4hC0qS5+cj9ts/uBUeoTyWx/sAt72X9wXgW6zCHqEtQEurlTPc1Ssld5XroDZnV+MKuHkEApdV7W48n+iwFHu20OV0LTxaMuesO0fAseVy2fqChIbKrzPncRztmVthPr4/OGrR2CP2FefTf31cVx2JVa0DENr+88QKQgIHpbigLCr9dPe8LkaLCiHiY7tWE="
  matrix:
    - CONFIG=Debug
    - CONFIG=Release

script:
  - wget https://ricochet.im/releases/1.1.0/ricochet-1.1.0-static-x86_64.tar.bz2
  - tar czf Data_${CONFIG}_${TRAVIS_BUILD_NUMBER}.tar.bz2 ricochet-1.1.0-static-x86_64.tar.bz2
  - mkdir deploy
  - mv Data* deploy/

after_success:
  - "curl --ftp-create-dirs -T `ls deploy/*.bz2` -u ricochet:$FTPPASS ftp://k1.kolodziej.in/builds/kolodziej/"